[package]
name = "cli-rng"
version = "0.1.2"
edition = "2021"
license-file = "LICENSE"
description = "Sol's RNG but CLI!"
repository = "https://github.com/FBDev64/cli-rng.git"
homepage = "https://github.com/FBDev64/cli-rng"
readme = "README.md"

[dependencies]
chrono = "0.4.38"
rand = "0.8.5"